baseURL = 'https://www.vsim.ca/'
languageCode = 'en-ca'
title = 'Vancouver School of Irish Music'
[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

# defaultContentLanguage = "en"
sectionPagesMenu = "main"

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

contentDir = "content"
languageCode = 'en-CA'


[params]
mainSections = ["post"]
text_color = ""
author = "" # "Vancouver School of Irish Music" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = ""
description = "Sharing the traditional music of Ireland in a welcoming, friendly environment."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 6 # 3

[params.ananke.social.follow]
networks = [
  "facebook",
  "instagram"
]

[params.ananke.social.facebook]
username = "vanschoolirishmusic"
# profilelink = "https://www.facebook.com/vanschoolirishmusic"

[params.ananke.social.instagram]
username = "vanschoolirishmusic"
# profilelink = "https://www.instagram.com/vanschoolirishmusic"
